version = 0.1
[dev]
[dev.deploy]
[dev.deploy.parameters]
stack_name = "dev-lms-lmsUser-service"
s3_bucket = "com.tekcapzule.api.deployment.dev"
s3_prefix = "dev-lms-lmsUser-service"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Stage=\"dev\""
image_repositories = []

[prod]
[prod.deploy]
[prod.deploy.parameters]
stack_name = "prod-lms-lmsUser-service"
s3_bucket = "com.tekcapzule.api.deployment.prod"
s3_prefix = "prod-lms-lmsUser-service"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Stage=\"prod\" Environment=\"prod\""
image_repositories = []

[dafault.deploy.parameters]
stack_name = "dev-lms-lmsUser-service"
resolve_s3 = true
s3_prefix = "dev-lms-lmsUser-service"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
parameter_overrides = "Stage=\"dev\""
image_repositories = []

[local.deploy.parameters]
stack_name = "dev-lms-lmsUser-service"
resolve_s3 = true
s3_prefix = "dev-lms-lmsUser-service"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
parameter_overrides = "Stage=\"dev\""
image_repositories = []

[default.deploy.parameters]
stack_name = "dev-lms-lmsUser-service"
resolve_s3 = true
s3_prefix = "dev-lms-lmsUser-service"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
parameter_overrides = "Stage=\"dev\""
image_repositories = []
